### PR TITLE
Created CEL MongoDB module

### PR DESCRIPTION
**Pull request by viktike**
I've written cel_mongodb.c

### CODE REVIEW

**Comment by minoruta** [comment]
Hi viktike,
Thank you for sharing your code. 👍 
I'll check it later.

**Comment by minoruta** [comment]
Hi, May I ask you trivial questions?
1. I probably found the author of the code in your code,
   on the other hand, didn't find any links between viktike@github and the author.
   Are you the owner of the code?
   # I apologize this can be rude question.
2. Your code doesn't mentioned any license.
   Do you agree the code belongs to GPL2?

**Comment by minoruta** [comment]
P.S.
I don't want to know who you are,
but want to confirm you have a right to disclose your valuable code with my repository as GPL2.
It is enough for me if you say 'yes'.

**Comment by viktike** [comment]
The code is written by me based on your cdr_mongodb.c, and I say yes.

**Comment by minoruta** [comment]
Grate! Thanks a lot. :^)

**Pull request merged**
